name: build_documentation

on:
  push:
    branches: [ master ]

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master

      # install Ascidoctor
      - name: install asciidoctor
        run: sudo gem install asciidoctor

      # show ascitoctor version
      - name: show version
        run: asciidoctor --version

      # install Ascidoctor-pdf
      - name: install asciidoctor-pdf
        run: sudo gem install asciidoctor-pdf --pre

      # show Ascidoctor-pdf version
      - name: show version
        run: asciidoctor-pdf -v

      # build
      - name: Build projektbericht
        run: asciidoctor-pdf --out-file=./docs/projektbericht/projektbericht.pdf ./docs/projektbericht/README.adoc

      # build
      - name: Build anforderungsanalyse
        run: asciidoctor-pdf --out-file=./docs/anforderung/anforderungsanalyse.pdf ./docs/anforderung/README.adoc

      #
      # Sphinx
      #
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: '3.8' # Semantic version range syntax or exact version of a Python version
          architecture: 'x64' # Optional - x64 or x86, defaults to x64

      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      # Install dependecies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Change directory and Build
      - name: Change directory + build sphinx
        run: |
          cd ./docs/
          ls -l
          sphinx-build ./sphinx/source/ .
          sphinx-build -b pdf ./sphinx/source/ ./sphinx/
          sphinx-build -b latex ./sphinx/source/ ./sphinx/latex/
          ls -l
          
      # Build pdf from sphinx/latex
      - name: Build PDF from latex
        uses: dante-ev/latex-action@master
        with:
          working_directory: ./docs/sphinx/latex/
          root_file: stura-mitgliederdatenbank.tex

      #
      # commit
      #
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git pull
          git commit -m "recreate documentation" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: cae14dd694317d892fb73708aae27506390ee20d
