name: doc_projectbericht+anforderungsanalyse

on:
  push:
    branches: [ master ]

jobs:
  projektbericht:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master

      # install Ascidoctor
      - name: install asciidoctor
        run: sudo gem install asciidoctor

      # show ascitoctor version
      - name: show version
        run: asciidoctor --version

      # install Ascidoctor-pdf
      - name: install asciidoctor-pdf
        run: sudo gem install asciidoctor-pdf --pre

      # show Ascidoctor-pdf version
      - name: show version
        run: asciidoctor-pdf -v

      # build
      - name: Build
        run: asciidoctor-pdf --out-file=./docs/projektbericht/projektbericht.pdf ./docs/projektbericht/README.adoc

      # commit
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add -A
          git commit -m "Add changes (Projektbericht)" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: cae14dd694317d892fb73708aae27506390ee20d

  anforderungsanalyse:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master

      # install Ascidoctor
      - name: install asciidoctor
        run: gem install asciidoctor

      # show ascitoctor version
      - name: show version
        run: asciidoctor --version

      # install Ascidoctor-pdf
      - name: install asciidoctor-pdf
        run: gem install asciidoctor-pdf --pre

      # show Ascidoctor-pdf version
      - name: show version
        run: asciidoctor-pdf -v

      # build
      - name: Build
        run: asciidoctor-pdf --out-file=./docs/anforderung/anforderungsanalyse.pdf ./docs/anforderung/README.adoc

      # commit
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add -A
          git commit -m "Add changes (Anforderungsanalyse)" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: cae14dd694317d892fb73708aae27506390ee20d
